remote_theme: pages-themes/cayman@v0.2.0
plugins:
  - jekyll-remote-theme # Enables GitHub remote themes
title: "Página de inicio Julián Cardozo Viggiano"
description: "En este repositorio iré compartiendo mis proyectos."
